### ISSUE TITLE
这个弹幕可以自定义形状颜色么 比如设置宽高 不想要阴影效果 也不想要边框

### ISSUE THREAD

**Issue by yrjwcharm** [slatejack/rc-bullets-ts#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/225908855-ec2caef5-b162-464b-bba5-b33e1715bfd6.png)

**Comment by yrjwcharm** [comment]
我想改变不要阴影效果，并且边框也不需要，

**Comment by slatejack** [comment]
可以的，可以自己封装一个弹幕item样式替换掉组件库自带的样式
```javascript
/**
* 发送自定义样式的弹幕
*/
const pushBullet = () => {
  screen.push(<SelefStyledBullet msg="测试弹幕"/>);
}
```

**Comment by yrjwcharm** [comment]
@slatejack  已经OK了。但是目前我这里又出现一个问题 
![image](https://user-images.githubusercontent.com/34397383/226170036-391aff37-6324-4258-b743-7bc0a06a9ff9.png)

**Comment by yrjwcharm** [comment]
就是两个图表高度完全相同，两个bullet 实例 ，他们分别push  漂浮时却不在相同的位置 即不在相同的轨道，这种该怎么解决呢

**Comment by yrjwcharm** [comment]
@slatejack  是否这两个实例可以添加个参数 保证他们轨道统一呢 ，还是有什么方法处理呢

**Comment by slatejack** [comment]
不太懂您的使用场景，这里的轨道是根据您容器高度动态计算出来的空余轨道，放置弹幕时优先取空域轨道进行放置
可以看下源代码
```javascript
 /**
   * 获取播放轨道
   * @returns 
   */
  private _getTrack() {
    const readyIdxs: number[] = [];
    let idx = -1;
    // 优先取空闲状态的
    this.tracks.forEach((status, index) => {
      if (status === 'idle') {
        readyIdxs.push(index);
      }
    });
    if (readyIdxs.length) {
      idx = readyIdxs[Math.floor(Math.random() * readyIdxs.length)];
    }
    if (idx === -1) {
      // 其次是可以接上状态的
      this.tracks.forEach((status, index) => {
        if (status === 'feed') {
          readyIdxs.push(index);
        }
      });
      if (readyIdxs.length) {
        idx = readyIdxs[Math.floor(Math.random() * readyIdxs.length)];
      }
    }
    // 如果此时状态值不等于-1，则说明该轨道在占用中
    if (idx !== -1) {
      this.tracks[idx] = 'running';
    }
    return idx;
  }
```

**Comment by yrjwcharm** [comment]
@slatejack  screen.clear([<bulletId>]) 弹幕清屏方法不生效是什么原因

**Comment by slatejack** [comment]
> @slatejack screen.clear([]) 弹幕清屏方法不生效是什么原因

不带参数才是清空全部
参考文档：https://github.com/slatejack/rc-bullets-ts#%E5%B8%B8%E7%94%A8-api

**Comment by yrjwcharm** [comment]
@slatejack   但是我 screen.clear();这个方法调用了
弹幕上还有滚动的文字

**Comment by yrjwcharm** [comment]
现在我是每次轮训请求一条数据，push 后 ，然后点击关闭屏幕想清屏 但是没反应

**Comment by slatejack** [comment]
> 现在我是每次轮训请求一条数据，push 后 ，然后点击关闭屏幕想清屏 但是没反应

您好，如果方便的话麻烦请提供一个最小实现的代码

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/227083988-8a23508f-408e-41ed-a459-886ae4522425.png)
主要就是这段代码。然后我调用那个方法 清屏不了
