### ISSUE TITLE
切换到其它tab页，过一会再切回来，最新接收到的弹幕直接不渲染在页面上了，或者直接一排排的渲染样式

### ISSUE THREAD

**Issue by jyxu1016** [slatejack/rc-bullets-ts#17]
**Describe the bug**
切换到其它tab页，过一会再切回来，最新接收到的弹幕直接不渲染在页面上了，或者直接一排排的渲染样式

**To Reproduce**
1. 切换到其它tab页，过一会再切回来

**Expected behavior**
组件内部监听当容器屏幕尺寸大小改变或再次切回到当前tab的时候，重置下呢，
，或者提供一个类似resize()的api给到开发者自己去重置？

**Screenshots**
当容器屏幕尺寸大小改变或再次切回到当前tab的时候，目前发现的弹幕异常表现：
<img width="401" alt="企业微信截图_17067758017957" src="https://github.com/slatejack/rc-bullets-ts/assets/84429503/28a9bccf-ff69-4fd4-beca-4f3c0f2d1ad9">

<img width="399" alt="企业微信截图_17067758108157" src="https://github.com/slatejack/rc-bullets-ts/assets/84429503/0a2cf01e-dd98-439a-a94b-877f338ffb36">

**Comment by slatejack** [comment]
收到issue，新版本上线会在此告知

**Comment by slatejack** [comment]
@jyxu1016 请升级至1.4.0版本，已支持resize()~

**Comment by hexinkui** [comment]
针对200字弹幕情况，重叠，有办法处理吗

**Comment by slatejack** [comment]
> 针对200字弹幕情况，重叠，有办法处理吗

你好 建议新开一个issue描述具体的问题 如有可能可附上图片辅助
