### ISSUE TITLE
delay 参数貌似没起作用

### ISSUE THREAD

**Issue by jacklee1177** [slatejack/rc-bullets-ts#23]
我有个单轨道的弹幕，需要一直加载数据push进来, 为了防止重叠得设置一下delay

```
if (comments && screenRef1.current) {
      comments.map((comment, index) => {
        screenRef1.current?.push(
          <CommentBarrageItem comment={comment}/>,
          {
            delay: index*2
          }
        )
      });
    }
```

但是貌似没起作用。我还需要一直加载下一页的数据，每条数据得根据内容长度计算delay时间，请教有什么好的方法实现吗

**Comment by slatejack** [comment]
1. 按照你逻辑执行是可以执行出延迟播放的效果的，需要您附上更详细的代码
2. 不建议用map来做这里的循环，这里只涉及遍历不涉及生成新的数组对象，建议替换为`for...of` or `for`
3. 如果需要一直往内加数据，建议手动维护一个list, 把每次新增的弹幕填充进list，再设定一个定时器每次取出list header用于展示

**Comment by jacklee1177** [comment]
感谢，我得问题，轨道高度不对，overflow hidden了
