### ISSUE TITLE
请问怎么配置弹道数量

### ISSUE THREAD

**Issue by 80666881** [slatejack/rc-bullets-ts#26]

**Comment by slatejack** [comment]
目前是通过指定单条弹道高度来计算容器内弹道数量的，暂不支持直接指定弹道数量

**Comment by 80666881** [comment]
> 目前是通过指定单条弹道高度来计算容器内弹道数量的，暂不支持直接指定弹道数量

好的，感谢，另外请问弹幕选取弹道的逻辑是什么？我播放弹幕时经常会出现部分弹幕一直挤在同一条弹道，或者后面弹幕遮挡前面弹幕的问题

**Comment by slatejack** [comment]
可以看下源码，逻辑是优先选取空闲通道进行弹幕投放，如出现上述问题建议先更新到最新版观察是否复现，如果复现需要解决需要提供对应的具体场景及相关可以复现的代码

**Comment by 80666881** [comment]
> 可以看下源码，逻辑是优先选取空闲通道进行弹幕投放，如出现上述问题建议先更新到最新版观察是否复现，如果复现需要解决需要提供对应的具体场景及相关可以复现的代码

@slatejack 原因就是弹幕有的长，有的短，设置播放时间后，短的速度会比较快，有可能覆盖掉前面的

**Comment by slatejack** [comment]
这点我理解算是正常可接受的范围，各大视频视频网站的弹幕如果数量过多也是直接按重叠处理的，如果有考虑做防遮挡弹幕，建议在push前手动处理延迟

**Comment by slatejack** [comment]
这边先关闭这个issue了，如后续还有问题可以继续在这里提问~
