### ISSUE TITLE
为什么暂停和继续播放后弹幕会变得只在固定轨道上播放

### ISSUE THREAD

**Issue by surelyNextTime** [slatejack/rc-bullets-ts#5]
如图，在演示页面也可以复现
![image](https://github.com/slatejack/rc-bullets-ts/assets/128406482/614bd814-1bf4-42e6-bbbc-8c120a7fb9e2)

**Comment by slatejack** [comment]
已收到反馈，这两天有时间看看处理下

**Comment by slatejack** [comment]
@surelyNextTime 已修复，升级至v1.1.1版本再看看呢
