### ISSUE TITLE
能指定弹幕区域吗？

### ISSUE THREAD

**Issue by gebaoyuanandy** [slatejack/rc-bullets-ts#9]
目前只有一个top值设置，是否可以加下bottom之类的设置半屏 全屏，顶部之类的？

**Comment by slatejack** [comment]
可以，根据issue可以新增一个bottom属性用于指定距离底部的距离

**Comment by slatejack** [comment]
@gebaoyuanandy 请升级到1.3.0版本，已支持bottom属性
